let InfoHeader = new Image();
InfoHeader.src = "GameModel/UI/PanelHeader.png"
let GrapesModel = new Image();
GrapesModel.src = "GameModel/Object/Eat/Виноград.png"
let CherryModel = new Image();
CherryModel.src = "GameModel/Object/Eat/Вишня.png"
let KiwiModel = new Image();
KiwiModel.src = "GameModel/Object/Eat/Киви.png"
let StrawberryModel = new Image();
StrawberryModel.src = "GameModel/Object/Eat/Клубника.png"
let MangoModel = new Image();
MangoModel.src = "GameModel/Object/Eat/Манго.png"
let AppleModel = new Image();
AppleModel.src = "GameModel/Object/Eat/Яблоко.png"
let COVIDModel = new Image();
COVIDModel.src = "GameModel/Object/COVID.png"
let PlayerModel = new Image();
PlayerModel.src = "GameModel/Player/PlayerModel.png"